# Generated by Django 5.0.2 on 2024-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facultyform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('faculty_id', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('B.com', 'B.com'), ('Engineering', 'Engineering'), ('Architecture', 'Architecture')], max_length=15)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
