# Generated by Django 5.0.2 on 2024-03-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lkp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
