# Generated by Django 5.0.2 on 2024-03-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkp', '0004_alter_feedback_options_alter_feedback_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='text_files/')),
            ],
        ),
    ]
