# Generated by Django 5.0.2 on 2024-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkp', '0005_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=50)),
                ('s_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='file',
            field=models.FileField(upload_to='text_file/'),
        ),
    ]
