# Generated by Django 5.0.2 on 2024-03-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkp', '0006_semester_alter_subject_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
