# Generated by Django 5.0.2 on 2024-03-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkp', '0007_semester_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.CharField(max_length=50)),
                ('d_name', models.CharField(max_length=50)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkp.semester')),
            ],
        ),
    ]
